[package]
name = "pcap"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
edition = "2018"

[dependencies]
error-chain = "~0.12"
futures-preview = { version ="0.3.0-alpha.10", features = ["compat"] }
libc = "~0.2"
log = "~0.4"
pcap-sys = { git = "https://github.com/protectwise/pcap-sys.git" }
pin-utils = "0.1.0-alpha.3"
tokio-timer = "~0.2"

[dev-dependencies]
env_logger = "~0.6"